abstract: convenient access to hierarchical data
author: Hans Dieter Pearcey <hdp@cpan.org>
build_requires: 
  Test::More: 0
  Test::use::ok: 0
distribution_type: module
generated_by: Module::Install version 0.57
license: perl
name: Data-Hive
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp::Clan: 0
version: 0.02
